# Generated by Django 5.2.14 on 2026-05-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
