# Generated by Django 5.2.14 on 2026-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Login',
        ),
    ]
