# Generated by Django 5.2.14 on 2026-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_message_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='message',
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(default=True, max_length=14),
        ),
    ]
