# Generated by Django 5.2.14 on 2026-05-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_remove_login_message_login_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='last',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
